version: '2'
services:
  web:
    image: roest/elefantenjagdverein.de:latest
  redis:
    image: redis:alpine
    volumes:
    - /srv/docker/ejv/data:/data
    command:
    - redis-server
    - --appendonly
    - 'yes'