version: '2.2'
volumes:
  redis_data:
services:
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/usr/local/var/db/redis/
  web:
    image: "registry.amicaldo.net:5000/amicaldo/elefantenjagdverein:v1.3"
    ports:
     - "80:80"
     - "3000:3000"
    depends_on:
      - redis