version: '2'
services:
  redis:
    image: "redis:alpine"
    volumes:
      - /srv/docker_volumes/ejv_data:/data
  web:
    image: "registry.amicaldo.net:5000/amicaldo/elefantenjagdverein:v1.3"
    depends_on:
      - redis